<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>EntApp.Modules.StateFlow.Infrastructure</RootNamespace>
    <NoWarn>$(NoWarn);CA2007;CA1062</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Stateless" Version="5.*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\EntApp.Modules.StateFlow.Application\EntApp.Modules.StateFlow.Application.csproj" />
    <ProjectReference Include="..\..\..\Shared\EntApp.Shared.Infrastructure\EntApp.Shared.Infrastructure.csproj" />
  </ItemGroup>
</Project>
