<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>EntApp.Modules.KnowledgeBase.Application</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.*" />
    <PackageReference Include="MediatR.Contracts" Version="2.*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\EntApp.Modules.KnowledgeBase.Domain\EntApp.Modules.KnowledgeBase.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\EntApp.Shared.Contracts\EntApp.Shared.Contracts.csproj" />
  </ItemGroup>
</Project>
